Fix firstboot fully installed detection
Before this I think it always said "It appears that Windows installation
was not completed in disk.qcow2" no matter what, because Temp folder can
be empty and logfile name was incorrect.

diff --git a/bvm b/bvm
--- a/bvm
+++ b/bvm
@@ -1010,9 +1010,12 @@ To get a fresh VM up and running, use a sequence like this:
     
     #check disk.qcow2 and remove microsoft defender if debloat enabled
     mountpoint="/media/$USER/bvm-mount$rdp_port"
-    if ! (mount_qcow2 "$vmdir/disk.qcow2") || [ ! -f "$mountpoint/Windows/Temp/setup_log.txt" ];then #check for the log left behind by my firstlogin.ps1 script to determine if it was fully installed
+    if ! (mount_qcow2 "$vmdir/disk.qcow2") ;then
       (unmount_qcow2)
-      error "It appears that Windows installation was not completed in disk.qcow2"
+      error "It appears that Windows installation was not completed in disk.qcow2. Mounting the hard disk image failed."
+    elif [ ! -f "$mountpoint/Program Files/Qemu-ga/qemu-ga.exe" ];then #check for qemu guest agent to determine if it was fully installed
+      (unmount_qcow2)
+      error "It appears that Windows installation was not completed in disk.qcow2. C:/Program Files/Qemu-ga/qemu-ga.exe does not exist."
     fi
     if [ "$debloat" == true ];then
       defenderfound=0
